# Generated by Django 4.1 on 2026-06-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EixoTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
