# Generated by Django 4.1 on 2026-06-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0002_eixotecnologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eixotecnologia',
            name='nome',
            field=models.CharField(max_length=60),
        ),
    ]
