# Generated by Django 4.1 on 2026-06-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0003_alter_eixotecnologia_nome'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autor',
            table='autor',
        ),
        migrations.AlterModelTable(
            name='eixotecnologia',
            table='eixo',
        ),
    ]
