# Generated by Django 4.2.30 on 2026-06-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0006_alter_artigo_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='data_publicaçao',
            new_name='data_publicacao',
        ),
        migrations.AlterField(
            model_name='artigo',
            name='texto',
            field=models.TextField(),
        ),
    ]
