# Generated by Django 4.2.30 on 2026-06-26 17:54

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0007_rename_data_publicaçao_artigo_data_publicacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={'ordering': ['-data_publicacao'], 'verbose_name': 'Artigo', 'verbose_name_plural': 'Artigos'},
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='eixotecnologia',
            options={'verbose_name': 'Eixo de Tecnologia', 'verbose_name_plural': 'Eixos de Tecnologia'},
        ),
        migrations.AddField(
            model_name='artigo',
            name='nivel',
            field=models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], default='B', max_length=1, verbose_name='Nível'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='id_fk_autor',
            field=models.ForeignKey(db_column='id_fk_autor', on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='motorartigos.autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='id_fk_eixo',
            field=models.ForeignKey(db_column='id_fk_eixo', on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='motorartigos.eixotecnologia', verbose_name='Eixo'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='texto',
            field=tinymce.models.HTMLField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='eixotecnologia',
            name='nome',
            field=models.CharField(max_length=60, verbose_name='Nome'),
        ),
    ]
