# Generated by Django 4.2.30 on 2026-06-30 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0008_alter_artigo_options_alter_autor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eixotecnologia',
            options={},
        ),
        migrations.AddField(
            model_name='artigo',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='id_fk_autor',
            field=models.ForeignKey(db_column='id_fk_autor', on_delete=django.db.models.deletion.CASCADE, to='motorartigos.autor'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='id_fk_eixo',
            field=models.ForeignKey(db_column='id_fk_eixo', on_delete=django.db.models.deletion.CASCADE, to='motorartigos.eixotecnologia'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='nivel',
            field=models.CharField(default='Sem nível', max_length=20, verbose_name='Nível'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eixotecnologia',
            name='nome',
            field=models.CharField(max_length=60),
        ),
    ]
